In [5]:
# ============================================================
# Experiment 2: Introduction to NumPy Arrays and Operations
# ============================================================

# Import NumPy
import numpy as np
print("NumPy Version:", np.__version__)
# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
# 2D Array
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 0D Array (Scalar)
arr_0d = np.array(42)

# 3×3 Array of Ones
arr_ones = np.ones((3, 3))

print("\n1D Array:")
print(arr_1d)

print("\n2D Array:")
print(arr_2d)

print("\n0D Array:")
print(arr_0d)

print("\n3×3 Array of Ones:")
print(arr_ones)

print("\nElement at index 2 in 1D array:", arr_1d[2])

print("Element at row 1, column 2 in 2D array:", arr_2d[1, 2])

print("Slice from 1D array:", arr_1d[1:4])

print("Second row of 2D array:", arr_2d[1, :])

arr_a = np.array([10, 20, 30])
arr_b = np.array([1, 2, 3])

print("\nArray A:", arr_a)
print("Array B:", arr_b)

print("Addition:", arr_a + arr_b)
print("Subtraction:", arr_a - arr_b)
print("Multiplication:", arr_a * arr_b)
print("Division:", arr_a / arr_b)
print("Scalar Multiplication:", arr_a * 2)

print("\nSum:", np.sum(arr_a))
print("Mean:", np.mean(arr_a))
print("Standard Deviation:", np.std(arr_a))


print("\nElement-wise Comparison (arr_a > arr_b):")
print(arr_a > arr_b)

print("Elements greater than 15:")
print(arr_a[arr_a > 15])

indices = [0, 2]

print("Selected Elements using Fancy Indexing:")
print(arr_a[indices])

reshaped_arr = arr_1d.reshape(5, 1)

print("\nReshaped 1D Array to 5×1:")
print(reshaped_arr)

structured_arr = np.array(
    [(25, 90.5), (30, 85.2)],
    dtype=[('age', 'i4'), ('score', 'f4')]
)

print("\nStructured Array:")
print(structured_arr)

print("\nAges:")
print(structured_arr['age'])

print("Scores:")
print(structured_arr['score'])

NumPy Version: 2.2.6

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

0D Array:
42

3×3 Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Element at index 2 in 1D array: 3
Element at row 1, column 2 in 2D array: 6
Slice from 1D array: [2 3 4]
Second row of 2D array: [4 5 6]

Array A: [10 20 30]
Array B: [1 2 3]
Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Scalar Multiplication: [20 40 60]

Sum: 60
Mean: 20.0
Standard Deviation: 8.16496580927726

Element-wise Comparison (arr_a > arr_b):
[ True  True  True]
Elements greater than 15:
[20 30]
Selected Elements using Fancy Indexing:
[10 30]

Reshaped 1D Array to 5×1:
[[1]
 [2]
 [3]
 [4]
 [5]]

Structured Array:
[(25, 90.5) (30, 85.2)]

Ages:
[25 30]
Scores:
[90.5 85.2]
